// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAIBojjbALrA0QcbWuNU7c6mHbdy6noiU',
    appId: '1:838693518963:web:0f5a0eee9a2a64803eb406',
    messagingSenderId: '838693518963',
    projectId: 'flutter-1cda7',
    authDomain: 'flutter-1cda7.firebaseapp.com',
    databaseURL: 'https://flutter-1cda7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-1cda7.firebasestorage.app',
    measurementId: 'G-JY8BYQKVCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpqL7hvVLTCa1Nh12eM0q_J2pCP1LHEpo',
    appId: '1:838693518963:android:ceb26fcf6095efb33eb406',
    messagingSenderId: '838693518963',
    projectId: 'flutter-1cda7',
    databaseURL: 'https://flutter-1cda7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-1cda7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5P0DLzZE4uOYWVozkvu7NeLG-wJlFBGQ',
    appId: '1:838693518963:ios:a508016078bfa3443eb406',
    messagingSenderId: '838693518963',
    projectId: 'flutter-1cda7',
    databaseURL: 'https://flutter-1cda7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-1cda7.firebasestorage.app',
    iosBundleId: 'com.example.charity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5P0DLzZE4uOYWVozkvu7NeLG-wJlFBGQ',
    appId: '1:838693518963:ios:a508016078bfa3443eb406',
    messagingSenderId: '838693518963',
    projectId: 'flutter-1cda7',
    databaseURL: 'https://flutter-1cda7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-1cda7.firebasestorage.app',
    iosBundleId: 'com.example.charity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBubpsWOjRg2Cb_Gy1jpqc66-poX6_hUpM',
    appId: '1:838693518963:web:0568e7ab4b3c0ece3eb406',
    messagingSenderId: '838693518963',
    projectId: 'flutter-1cda7',
    authDomain: 'flutter-1cda7.firebaseapp.com',
    databaseURL: 'https://flutter-1cda7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-1cda7.firebasestorage.app',
    measurementId: 'G-8L16G15S5N',
  );
}
